class RustPanicException(Exception): ...

def byte_swap(infile: str, outfile: str) -> None: ...
def endian_swap(infile: str, outfile: str) -> None: ...
def byte_endian_swap(infile: str, outfile: str) -> None: ...
