# Typed Stubs for n64romconvert

class RustPanicException(Exception): ...

def determine_format(path: str) -> str: ...
def byte_swap(infile: str, outfile: str) -> None: ...
def endian_swap(infile: str, outfile: str) -> None: ...
def byte_endian_swap(infile: str, outfile: str) -> None: ...
